#!/usr/bin/env python3

import subprocess
import threading
import code

def repl(**locals):
    from pprint import pprint
    locals['pp'] = pprint
    code.InteractiveConsole(locals).interact()

def thread(target, *args, **kwargs):
    t = threading.Thread(target=target, args=args, kwargs=kwargs, daemon=True)
    t.start()

def printloop(f):
    while True:
        print(f.read(60))

def run(args):
    p = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    try:
        thread(printloop, p.stdout)
        repl(p=p)
    finally:
        print('at exit', p.pid)
        p.kill()
        print('exit code:', p.wait())

if __name__ == '__main__':
    import sys
    run(sys.argv[1:])
